export const Languages = [
        { code: 'en', name: 'English', nativeName: 'English' },
        { code: 'zh', name: 'Chinese (Mandarin)', nativeName: '中文' },
        { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
        { code: 'es', name: 'Spanish', nativeName: 'Español' },
        { code: 'fr', name: 'French', nativeName: 'Français' },
        { code: 'ar', name: 'Classical Arabic', nativeName: 'العربية' },
        { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
        { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
        { code: 'ru', name: 'Russian', nativeName: 'Русский' },
        { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
        { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
        { code: 'de', name: 'German', nativeName: 'Deutsch' },
        { code: 'ja', name: 'Japanese', nativeName: '日本語' },
        { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
        { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
        { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
        { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
        { code: 'ko', name: 'Korean', nativeName: '한국어' },
        { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
        { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
        { code: 'it', name: 'Italian', nativeName: 'Italiano' },
        { code: 'th', name: 'Thai', nativeName: 'ไทย' },
        { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
        { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa' },
        { code: 'fa', name: 'Persian (Farsi)', nativeName: 'فارسی' },
        { code: 'pl', name: 'Polish', nativeName: 'Polski' },
        { code: 'uk', name: 'Ukrainian', nativeName: 'Українська' },
        { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
        { code: 'ro', name: 'Romanian', nativeName: 'Română' },
        { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
        { code: 'hu', name: 'Hungarian', nativeName: 'Magyar' },
        { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
        { code: 'cs', name: 'Czech', nativeName: 'Čeština' },
        { code: 'he', name: 'Hebrew', nativeName: 'עברית' },
        { code: 'da', name: 'Danish', nativeName: 'Dansk' },
        { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
        { code: 'no', name: 'Norwegian', nativeName: 'Norsk' }
      ]
